"""LangChain to AI SDK Adapter.

A Python package that converts LangChain/LangGraph event streams to AI SDK UI Stream Protocol format.
"""

from .adapter import (
    # Main API functions (AI SDK compatible)
    to_data_stream,
    to_data_stream_response,
    merge_into_data_stream,
)
from .callbacks import (
    BaseAICallbackHandler,
    StreamCallbacks,
    CallbacksTransformer,
)
from .callbacks import (
    Message,
    TextUIPart,
    ReasoningUIPart,
    ToolInvocation,
    ToolInvocationUIPart,
    SourceUIPart,
    FileUIPart,
    StepStartUIPart,
    ErrorUIPart,
    UIPart,
    Attachment,
    LanguageModelUsage,
    JSONValue,
)
from .models import (
    LangChainAIMessageChunk,
    LangChainMessageContent,
    LangChainMessageContentComplex,
    LangChainMessageContentImageUrl,
    LangChainMessageContentText,
    LangChainStreamEvent,
    UIMessageChunk,
    ProviderMetadata,
    UIMessageChunkTextStart,
    UIMessageChunkTextDelta,
    UIMessageChunkTextEnd,
    UIMessageChunkError,
    UIMessageChunkToolInputStart,
    UIMessageChunkToolInputDelta,
    UIMessageChunkToolInputAvailable,
    UIMessageChunkToolOutputAvailable,
    UIMessageChunkToolOutputError,
    UIMessageChunkReasoning,
    UIMessageChunkReasoningStart,
    UIMessageChunkReasoningDelta,
    UIMessageChunkReasoningEnd,
    UIMessageChunkReasoningPartFinish,
    UIMessageChunkSourceUrl,
    UIMessageChunkSourceDocument,
    UIMessageChunkFile,
    UIMessageChunkData,
    UIMessageChunkStartStep,
    UIMessageChunkFinishStep,
    UIMessageChunkStart,
    UIMessageChunkFinish,
    UIMessageChunkAbort,
    UIMessageChunkMessageMetadata,
)

__version__ = "0.0.1a1"

__all__ = [
    # Main API functions (AI SDK compatible)
    "to_data_stream",
    "to_data_stream_response",
    "merge_into_data_stream",
    # Callback system
    "BaseAICallbackHandler",
    "StreamCallbacks",
    "CallbacksTransformer",
    # Data models
    "Message",
    "TextUIPart",
    "ReasoningUIPart",
    "ToolInvocation",
    "ToolInvocationUIPart",
    "SourceUIPart",
    "FileUIPart",
    "StepStartUIPart",
    "ErrorUIPart",
    "UIPart",
    "Attachment",
    "LanguageModelUsage",
    "JSONValue",
    "LangChainAIMessageChunk",
    "LangChainMessageContent",
    "LangChainMessageContentComplex",
    "LangChainMessageContentImageUrl",
    "LangChainMessageContentText",
    "LangChainStreamEvent",
    "UIMessageChunk",
    "ProviderMetadata",
    "UIMessageChunkTextStart",
    "UIMessageChunkTextDelta",
    "UIMessageChunkTextEnd",
    "UIMessageChunkError",
    "UIMessageChunkToolInputStart",
    "UIMessageChunkToolInputDelta",
    "UIMessageChunkToolInputAvailable",
    "UIMessageChunkToolOutputAvailable",
    "UIMessageChunkToolOutputError",
    "UIMessageChunkReasoning",
    "UIMessageChunkReasoningStart",
    "UIMessageChunkReasoningDelta",
    "UIMessageChunkReasoningEnd",
    "UIMessageChunkReasoningPartFinish",
    "UIMessageChunkSourceUrl",
    "UIMessageChunkSourceDocument",
    "UIMessageChunkFile",
    "UIMessageChunkData",
    "UIMessageChunkStartStep",
    "UIMessageChunkFinishStep",
    "UIMessageChunkStart",
    "UIMessageChunkFinish",
    "UIMessageChunkAbort",
    "UIMessageChunkMessageMetadata",
]